spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toutiao?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 1230
  thymeleaf:
    cache: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.cr.toutiao.mapper: debug
